import React, { useState } from 'react';
import {
  X,
  Mail,
  RefreshCw,
  CheckCircle2,
  Copy,
  Check,
  ExternalLink,
  ShieldCheck,
  Send,
  AlertCircle,
} from 'lucide-react';
import { WaterfallRow } from '../types';

interface RefreshDataModalProps {
  rows: WaterfallRow[];
  isOpen: boolean;
  onClose: () => void;
  onConfirmRefresh: (emailPayload: {
    recipients: string[];
    subject: string;
    body: string;
    customNote: string;
  }) => void;
}

export const RefreshDataModal: React.FC<RefreshDataModalProps> = ({
  rows,
  isOpen,
  onClose,
  onConfirmRefresh,
}) => {
  const [customRecipient, setCustomRecipient] = useState('');
  const [customNote, setCustomNote] = useState('');
  const [copied, setCopied] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  if (!isOpen) return null;

  const defaultRecipients = [
    'marcus.vance.pmo@enterprise.bank', // PMO Lead
    'sarah.jenkins@enterprise.bank',    // FRC Director
    'alex.morgan@enterprise.bank',      // Lead Analyst
    'waterfall.team@enterprise.bank',   // Project Team
  ];

  const allRecipients = customRecipient.trim() && customRecipient.includes('@')
    ? [...defaultRecipients, customRecipient.trim()]
    : defaultRecipients;

  const timestamp = new Date().toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZoneName: 'short',
  });

  const subject = `[Waterfall Alert] Full Analytical Refresh Initiated across All Steps (${rows.length} Steps)`;

  const stepBulletPoints = rows.length > 0
    ? rows.map((r, idx) => `  ${idx + 1}. [WFID# ${r.id}] ${r.stepTitle} (Rule Ref: ${r.ruleReference || 'N/A'}) - Category: ${r.category}`).join('\n')
    : '  (No active waterfall steps currently in scope)';

  const bodyText = `Dear Waterfall Project Team & Leadership (PMO, FRC & Analytics),

Please be advised that an enterprise-wide "REFRESH DATA" event has been initiated across the entire Requirements Waterfall pipeline.

==================================================
REFRESH DATA DISPATCH SPECIFICATION
==================================================
• Event Trigger     : Full Analytical Pipeline Refresh
• Timestamp         : ${timestamp}
• Total Steps Scope : ${rows.length} active step(s)
• Status Intent     : All analytical steps queued for refreshed computation, data reassessment, and re-validation.
• Target Action     : Analysts are instructed to refresh underlying data extracts, re-evaluate exclusion filters, and update working day schedules.

==================================================
AFFECTED WATERFALL STEPS:
==================================================
${stepBulletPoints}

${customNote.trim() ? `==================================================\nANALYST REFRESH RATIONALE / NOTES:\n==================================================\n${customNote.trim()}\n` : ''}
==================================================
NEXT STEPS FOR PROJECT TEAM:
==================================================
1. Analytics Team: Re-run upstream data pipelines and update Include/Exclude case counts.
2. FRC Governance: Review any new variances or exceptions in the Waterfall Scoping table.
3. PMO: Track working days impact and schedule recalculations against baseline deliverables.

Automated notification generated by eGRC Waterfall Management Portal.`;

  const handleCopy = () => {
    try {
      navigator.clipboard.writeText(bodyText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // fallback
    }
  };

  const handleOpenMailto = () => {
    const to = encodeURIComponent(allRecipients.join(';'));
    const subj = encodeURIComponent(subject);
    const body = encodeURIComponent(bodyText);
    window.location.href = `mailto:${to}?subject=${subj}&body=${body}`;
  };

  const handleConfirm = () => {
    setIsSubmitting(true);
    onConfirmRefresh({
      recipients: allRecipients,
      subject,
      body: bodyText,
      customNote,
    });
    setIsSubmitting(false);
    onClose();
  };

  return (
    <div
      id="modal-refresh-data"
      className="fixed inset-0 z-50 bg-stone-900/60 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto animate-in fade-in duration-150"
    >
      <div className="bg-white rounded-2xl shadow-2xl border border-stone-200 w-full max-w-2xl overflow-hidden flex flex-col my-6 animate-in zoom-in-95 duration-200">
        {/* Modal Header */}
        <div className="bg-stone-900 text-white px-5 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-blue-600/30 border border-blue-400/40 flex items-center justify-center text-blue-300">
              <RefreshCw className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-bold tracking-tight">Refresh All Analytical Steps</h3>
              <p className="text-[11px] text-stone-300">
                Trigger email notification to Project Team to re-evaluate and refresh all steps
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="text-stone-400 hover:text-white p-1 rounded-lg hover:bg-stone-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-5 space-y-4 max-h-[75vh] overflow-y-auto">
          {/* Notification Info Banner */}
          <div className="bg-blue-50 border border-blue-200 rounded-xl p-3.5 flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-blue-700 shrink-0 mt-0.5" />
            <div className="text-xs text-blue-950 leading-relaxed">
              <span className="font-bold block">Enterprise Data Refresh Event</span>
              Clicking <strong>Send Email &amp; Refresh Data</strong> will register an audit transaction, update the steps' analytical sync status, and dispatch an email alert to all team members (PMO, FRC Owner &amp; Analytics).
            </div>
          </div>

          {/* Recipients Section */}
          <div>
            <label className="block text-xs font-bold text-stone-700 mb-1.5">
              Email Recipients (Primary Project Team)
            </label>
            <div className="bg-stone-50 p-2.5 rounded-xl border border-stone-200 text-xs space-y-2">
              <div className="flex flex-wrap gap-1.5">
                {defaultRecipients.map((email) => (
                  <span
                    key={email}
                    className="bg-white text-stone-800 font-mono text-[11px] px-2 py-0.5 rounded-md border border-stone-200"
                  >
                    {email}
                  </span>
                ))}
              </div>
              <div className="flex items-center gap-2 pt-1 border-t border-stone-200">
                <span className="text-[11px] font-medium text-stone-500 whitespace-nowrap">
                  + Add Additional CC:
                </span>
                <input
                  type="email"
                  placeholder="e.g. data.architect@enterprise.bank"
                  value={customRecipient}
                  onChange={(e) => setCustomRecipient(e.target.value)}
                  className="flex-1 px-2.5 py-1 text-xs bg-white border border-stone-300 rounded-lg focus:ring-2 focus:ring-stone-900 focus:outline-hidden font-mono"
                />
              </div>
            </div>
          </div>

          {/* Custom Note/Rationale */}
          <div>
            <label className="block text-xs font-bold text-stone-700 mb-1">
              Optional Refresh Rationale or Instruction
            </label>
            <textarea
              rows={2}
              value={customNote}
              onChange={(e) => setCustomNote(e.target.value)}
              placeholder="e.g. Refreshing with new Q3 credit portfolio extract, recomputing exclusion rules 2.1 through 2.4..."
              className="w-full px-3 py-2 text-xs bg-white border border-stone-300 rounded-xl focus:ring-2 focus:ring-stone-900 focus:outline-hidden resize-y text-stone-800"
            />
          </div>

          {/* Subject Line Preview */}
          <div>
            <label className="block text-xs font-bold text-stone-700 mb-1">Subject</label>
            <div className="bg-stone-100 px-3 py-2 rounded-xl border border-stone-300 text-xs font-semibold text-stone-800 font-mono">
              {subject}
            </div>
          </div>

          {/* Email Body Preview */}
          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="text-xs font-bold text-stone-700">Pre-compiled Email Body</label>
              <button
                type="button"
                onClick={handleCopy}
                className="text-xs text-blue-600 hover:text-blue-800 font-semibold flex items-center gap-1"
              >
                {copied ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-600" />
                    Copied to Clipboard!
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    Copy Body Text
                  </>
                )}
              </button>
            </div>
            <div className="bg-stone-950 text-stone-200 p-3.5 rounded-xl border border-stone-800 font-mono text-[11px] leading-relaxed max-h-52 overflow-y-auto whitespace-pre-wrap">
              {bodyText}
            </div>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="bg-stone-50 px-5 py-3.5 border-t border-stone-200 flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="text-[11px] text-stone-500 flex items-center gap-1.5">
            <ShieldCheck className="w-4 h-4 text-emerald-600" />
            <span>eGRC Automated Dispatch Service • Audit Registered</span>
          </div>

          <div className="flex items-center gap-2 w-full sm:w-auto">
            <button
              type="button"
              onClick={handleOpenMailto}
              className="px-3 py-2 bg-white hover:bg-stone-100 text-stone-700 text-xs font-semibold rounded-xl border border-stone-300 flex items-center justify-center gap-1.5 transition-colors shadow-2xs w-1/2 sm:w-auto"
              title="Open draft in system email client (Outlook, Gmail)"
            >
              <ExternalLink className="w-3.5 h-3.5 text-stone-600" />
              Open in Mail Client
            </button>

            <button
              type="button"
              disabled={isSubmitting}
              onClick={handleConfirm}
              className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-xl flex items-center justify-center gap-1.5 transition-colors shadow-xs w-1/2 sm:w-auto"
            >
              <Send className="w-3.5 h-3.5" />
              {isSubmitting ? 'Dispatching...' : 'Send Email & Refresh Data'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
